# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  HonseEngine_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  HonseEngine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW HonseEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C . -f GLFW.make config=$(GLFW_config)
endif

HonseEngine: GLFW
ifneq (,$(HonseEngine_config))
	@echo "==== Building HonseEngine ($(HonseEngine_config)) ===="
	@${MAKE} --no-print-directory -C . -f HonseEngine.make config=$(HonseEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f GLFW.make clean
	@${MAKE} --no-print-directory -C . -f HonseEngine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   HonseEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"